# action.yml
name: 'Agda GitHub action'
description: 'GitHub action for typechecking your Agda code'
inputs:
  main-file:
    description: 'Main file of the Agda development'
    required: true
    default: 'Main.agda'
  source-dir:
    description: 'The name of the directory where your code lives'
    required: true
    default: src
  unsafe:
    description: 'Do not use the --safe flag'
    required: false
    default: false
  html:
    description: 'Whether to generate HTML from Agda'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.main-file  }}
    - ${{ inputs.source-dir }}
    - ${{ inputs.unsafe     }}
    - ${{ inputs.html       }}
