# action.yml
name: 'Agda GitHub action'
description: 'GitHub action for typechecking your Agda code'
inputs:
  main-file:
    description: 'Main file of the Agda development'
    required: true
    default: 'Main.agda'
  source-dir:
    description: 'The name of the directory where your code lives'
    required: true
    default: src
runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: 'setup.sh'
  args:
    - ${{ inputs.main-file  }}
    - ${{ inputs.source-dir }}
