on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    name: A job to typecheck your Agda code
    steps:
    - name: Typechecking step
      id: typecheck
      uses: ayberkt/agda-github-action@v0
      with:
        main-file: Foo.agda
    - name: Print Agda version
      run: agda --version