on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    name: A job to typecheck your Agda code
    steps:
    - name: "Clone repository"
      uses: actions/checkout@v2
    - name: Typechecking step
      id: typecheck
      uses: ayberkt/agda-github-action@master
      with:
        main-file: Main.agda
        source-dir: example
    - run: ls
    - run: ls html
    - run: pwd
    - run: cp html/Main.html .
    - name: Upload HTML
      id: html-upload
      uses: actions/upload-artifact@v1
      with:
        name: Main.html
        path: Main.html