on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    name: A job to typecheck Agda code
    steps:
    - name: "Clone repository"
      uses: actions/checkout@v2
    - name: Typechecking step
      id: typecheck
      uses: ayberkt/agda-github-action@master
      with:
        main-file: Main.agda
        source-dir: example
        stdlib: true
    - name: Upload HTML
      id: html-upload
      uses: actions/upload-artifact@v1
      with:
        name: html
        path: example/html
